/** English presentation copy for the prepared adopter profiles and enquiries. */
export const adopterCopyTranslations: Record<string, string> = {
  "回答しない": "Prefer not to say", "30代": "30s", "20代": "20s", "40代": "40s", "50代": "50s", "60代": "60s",
  "神奈川県": "Kanagawa Prefecture", "京都府": "Kyoto Prefecture",
  "男性": "Male", "女性": "Female", "会社員・週3日在宅": "Employee; works from home three days a week",
  "フルタイム勤務・週3日在宅": "Full-time work; three days at home", "自営業・在宅勤務": "Self-employed; works from home",
  "会社員・シフト勤務": "Employee; shift work", "会社員・日勤": "Employee; daytime hours",
  "パート勤務": "Part-time work", "在宅勤務": "Works from home", "学生・アルバイト": "Student with part-time work",
  "退職後・非常勤": "Retired; occasional work", "会社員・在宅勤務": "Employee; works from home", "自営業": "Self-employed",
  "同居者全員が迎えることに同意しています。": "Everyone in the household agrees to adopt.",
  "本人が迎えることを希望し、近隣の支援者にも相談済みです。": "The applicant wishes to adopt and has discussed support with someone nearby.",
  "本人が迎えることを希望し、近隣の娘にも相談済みです。": "The applicant wishes to adopt and has discussed the plan with a nearby daughter.",
  "同居者に動物アレルギーの申告はありません。": "No household member has reported an animal allergy.",
  "先住動物はいません。": "There are no existing pets.",
  "ペット飼育可能な住居です。玄関と窓の脱走防止を計画しています。": "Pets are permitted in the home; escape prevention is planned for doors and windows.",
  "飼育規約を確認済みです。": "The pet policy has been checked.",
  "平日は4～6時間程度。不在時は家族が対応します。": "Away for around four to six hours on weekdays; family covers care during absences.",
  "本人が主に担当し、同居者が代わりに世話をします。": "The applicant provides primary care; a household member can substitute.",
  "本人が主に担当し、不在時は近隣の家族が世話をします。": "The applicant is the primary carer, with nearby family covering absences.",
  "本人が中心。勤務時は決めた支援者が代わります。": "The applicant is the main carer; an agreed helper covers work hours.",
  "過去に犬または猫と暮らした経験があります。": "Has previously lived with a dog or cat.",
  "食事・運動・健康観察の時間を朝夕に確保します。": "Sets aside morning and evening time for feeding, exercise and health checks.",
  "通院できる動物病院を確認し、夜間の連絡先も控えています。": "Has identified a veterinary practice and an out-of-hours contact.",
  "毎月の飼育費と急な受診費用を分けて備えています。": "Plans separately for routine care and unexpected veterinary costs.",
  "家族として迎え、必要なケアを続けたいと考えています。": "Wants to welcome the pet as family and maintain the care it needs.",
  "猫は初めてで、投薬方法を練習中です。": "New to cats and practising how to give medication.",
  "日によって8時間ほど。交代で世話をする家族がいます。": "Away for up to eight hours on some days; family members take turns caring.",
  "本人とパートナーが交代で担当します。": "The applicant and partner share care duties.",
  "大人3名と中学生1名です。": "Three adults and one secondary-school child live in the household.",
  "高齢の犬が1頭います。": "There is one senior dog in the home.",
  "朝夕に散歩を各40分、週末は長めに運動します。": "Plans 40-minute walks morning and evening, with longer exercise at weekends.",
  "管理規約の写しを提出予定です。": "Plans to submit a copy of the building's pet policy.",
  "家族1名に軽い猫アレルギーがあり、事前に医師へ相談します。": "One family member has a mild cat allergy; medical advice will be sought first.",
  "先住猫が1頭います。別室での段階的な対面を計画しています。": "There is one existing cat; introductions will be gradual, using separate rooms.",
  "継続して受診できる近所の動物病院を確認済みです。": "Has identified a nearby veterinary practice for continuing care.",
  "授業の日は6時間程度で、同居者が在宅しています。": "Away for around six hours on class days; a household member is at home.",
  "飼育費の目安を調べ、同居者と分担します。": "Has researched likely care costs and will share them with a household member.",
  "大人2名で暮らしています。": "Two adults live in the household.",
  "本人が中心。急病時は近隣の娘が支援します。": "The applicant is the main carer; a nearby daughter can help if they become ill.",
  "入院時は娘が一時預かりを引き受ける予定です。": "The daughter plans to provide temporary care during any hospital stay.",
  "小型犬が1頭います。対面は双方の様子を見ながら段階的に進めます。": "There is one small dog; introductions will proceed gradually according to both pets' reactions.",
  "ペット可の戸建てで庭はフェンスで囲っています。": "A pet-friendly house with a fenced garden.",
  "朝夕の給餌と散歩を本人が担当します。": "The applicant will handle morning and evening feeding and walks.",
  "投薬の時間と必要な通院について詳しく伺いたいです。": "I would like to ask about medication times and veterinary visits.",
  "静かな環境で迎えるための準備について相談したいです。": "I would like to discuss preparing a quiet home.",
  "朝夕の散歩と面談の日程について相談したいです。": "I would like to discuss morning and evening walks and a meeting date.",
  "先住犬との相性を確かめる方法を教えてください。": "How should I check compatibility with my existing dog?",
  "住居の飼育規約の確認について質問があります。": "I have a question about checking the home's pet policy.",
  "トライアル中の健康管理について伺いたいです。": "I would like to ask about health care during the trial.",
  "お迎え前に必要な準備を教えてください。": "What should I prepare before bringing the pet home?",
  "通院の負担を確認し、今回は相談を終了します。": "After considering the veterinary commitment, I am closing this enquiry.",
  "先住犬との同居条件を確認し、相談を終了します。": "After checking the conditions for living with my dog, I am closing this enquiry.",
  "朝夕の運動計画について相談したいです。": "I would like to discuss the morning and evening exercise plan.",
};
