/** English presentation copy for prepared consultation conversations. */
export const consultationCopyTranslations: Record<string, string> = {
  "あなた": "You",
  "審査担当者": "Reviewer",
  "審査へ進んだ相談": "Enquiries that proceeded to review",
  "審査前の相談": "Enquiries before review",
  "審査中": "Under review",
  "審査準備中": "Preparing for review",
  "相談のみ": "Enquiry only",
  "申込みを受け付け、審査工程に進んでいる相談です。": "These enquiries have become applications and entered the review process.",
  "担当者の返信待ち、プロファイルの提出準備中、または相談のみで終了した記録です。": "These records are awaiting a reply, preparing profile information, or ended as enquiries without entering review.",
  "お問い合わせありがとうございます。審査を希望される場合は、基本プロファイルと詳細プロファイルをご提出ください。": "Thank you for your enquiry. If you wish to apply, please submit your basic and additional profile information.",
  "基本プロファイルと詳細プロファイルを提出しました。追加で必要な情報があればお知らせください。": "I have submitted my basic and additional profile information. Please let me know if anything else is needed.",
  "朝夕の投薬は何時頃が目安でしょうか。平日の通院頻度についても詳しく伺いたいです。": "What times should the morning and evening medication be given? I would also like to know more about weekday vet visits.",
  "投薬は朝7時頃と夜19時頃が目安です。通院は現在3か月ごとですが、体調により追加受診があります。": "Medication is usually given around 7 a.m. and 7 p.m. Vet visits are currently every three months, with extra visits if health changes.",
  "平日も家族と分担して対応できます。かかりつけ候補の病院と移動手段をプロファイルに記載します。": "My family and I can share the weekday care. I will add our proposed veterinary practice and transport plan to my profile.",
  "提出内容を受領し、申込みを受け付けました。現在は適合性確認を進めています。": "We have received your information and accepted the application. The suitability review is now in progress.",
  "来客が少ない静かな家です。最初の数週間に用意すべき隠れ場所や生活スペースを教えてください。": "My home is quiet with few visitors. What hiding places and living space should I prepare for the first few weeks?",
  "最初は扉を閉められる一室に、隠れられる箱、トイレ、食器を離して置くことを勧めています。": "We recommend starting in a room that can be closed, with a hiding box, litter tray and food bowls placed apart.",
  "寝室横の個室を最初の生活スペースにできます。窓の脱走防止柵も設置予定です。": "I can use the spare room beside the bedroom as the initial space and plan to fit window escape guards.",
  "飼育許可書と住居の間取りを含めてプロファイルを提出しました。": "I submitted my profile with the pet permission document and home floor plan.",
  "提出書類を受領しました。現在は書類確認を進めています。追加資料が必要な場合はこの履歴でご連絡します。": "We received the documents and are reviewing them. We will use this message history if further evidence is required.",
  "平日は朝夕各40分ほど散歩できます。面談は土曜日を希望していますが、候補日はありますか。": "I can provide about 40 minutes of walking each morning and evening. Are Saturday meeting dates available?",
  "散歩計画をありがとうございます。まずプロファイルと住居情報を確認した後、面談候補日をご案内します。": "Thank you for the walking plan. We will suggest meeting dates after reviewing your profile and housing information.",
  "散歩計画をありがとうございます。Soraは朝夕に十分な運動が必要です。面談候補日はPawMatch運営の確認後に一緒に調整します。": "Thank you for the walking plan. Sora needs sufficient exercise every morning and evening. We will arrange meeting dates together after PawMatch operations completes its checks.",
  "書類確認まで完了したため、9月19日または20日の面談を調整できます。": "The document review is complete, so we can arrange a meeting on 19 or 20 September.",
  "9月20日の午前を希望します。同居する家族も参加できます。": "I would prefer the morning of 20 September. My household members can also attend.",
  "先住犬との相性を確かめる際、最初の対面はどのように行うのが安全でしょうか。": "How should the first meeting be managed safely when checking compatibility with my existing dog?",
  "最初は中立な屋外で距離を保ち、二人でそれぞれの犬を担当する方法を予定しています。": "We plan to begin outdoors in neutral territory, keeping distance, with one person handling each dog.",
  "先住犬は避妊済みで、混合ワクチンも接種済みです。証明書を提出できます。": "My dog is spayed and has current core vaccinations. I can provide the certificates.",
  "申込みを受け付けました。先住犬との段階的な導入計画について、現在追加確認を行っています。": "The application has been accepted. We are carrying out an additional check of the gradual introduction plan.",
  "賃貸住宅の飼育規約は、どのページを提出すればよいでしょうか。管理会社の承諾書も必要ですか。": "Which pages of my tenancy rules should I submit, and is written approval from the property manager required?",
  "動物の種類と頭数が確認できる規約ページをご提出ください。規約だけで判断できない場合は管理会社の承諾書もお願いします。": "Please submit the pages showing permitted species and numbers. We may also request property-manager approval if the rules are unclear.",
  "猫1頭まで可と記載された規約と、管理会社からのメールを用意できます。": "I can provide the rule allowing one cat and an email from the property manager.",
  "プロファイルと住居規約を提出しました。管理会社のメールも補足資料として登録しています。": "I submitted my profile and tenancy rules, with the property manager's email as supporting evidence.",
  "申込みを受け付け、書類確認を進めています。住居条件は確認済みです。": "The application has been accepted and document review is in progress. The housing requirement has been confirmed.",
  "トライアル中に食欲が落ちた場合の連絡先と、受診の判断基準を事前に確認したいです。": "Before the trial, I would like to confirm who to contact and when to seek veterinary care if appetite drops.",
  "食事を2回続けて取らない、嘔吐が続く、排尿がない場合はすぐに譲渡者へ連絡し、指定病院へ相談してください。": "Contact the rehomer and nominated vet promptly if two meals are missed, vomiting continues, or there is no urination.",
  "食事を2回続けて取らない、嘔吐が続く、排尿がない場合はすぐに私へ連絡し、指定病院へ相談してください。": "Contact me and the nominated vet promptly if two meals are missed, vomiting continues, or there is no urination.",
  "自宅から指定病院まで車で15分です。夜間病院の連絡先も登録します。": "The nominated vet is a 15-minute drive from my home. I will also record an emergency clinic contact.",
  "面談内容を双方で確認しました。現在はトライアル中です。毎日の食事量と排泄、体調を記録してください。": "Both parties confirmed the meeting record. The trial is now in progress; please record food, toileting and health each day.",
  "初めて犬を迎えます。留守番の練習と、最初に揃えるものについて相談したいです。": "This will be my first dog. I would like advice on practising time alone and what to prepare first.",
  "短時間から留守番を練習し、落ち着ける寝床、滑りにくい床材、脱走防止ゲートを準備してください。": "Practise short periods alone and prepare a calm bed, non-slip flooring and escape-prevention gates.",
  "準備できる環境を確認しました。審査を希望するため、必要な情報を教えてください。": "I have confirmed that I can prepare this environment. Please tell me what information is needed to apply.",
  "現在プロファイルと住居の資料を準備しています。提出まで数日お待ちください。": "I am preparing my profile and housing evidence. Please allow a few days for submission.",
  "定期通院の頻度と、体調が変化した場合に必要な対応を教えてください。": "Please explain the frequency of routine vet visits and what action is required if health changes.",
  "現在は3か月ごとの通院と朝夕の投薬が必要です。食欲低下や呼吸の変化がある場合は早めの受診をお願いします。": "Vet visits are currently every three months, with medication morning and evening. Prompt care is needed for appetite or breathing changes.",
  "勤務と通院先までの距離を考えると継続対応が難しいため、今回は申込みに進まず相談を終了したいです。": "Given my work and the distance to the clinic, I cannot reliably provide this care and would like to end the enquiry without applying.",
  "先住猫がいるため、別室で過ごす期間と対面を始める目安を確認したいです。": "I have an existing cat and would like guidance on the separation period and when to begin introductions.",
  "最初は完全に別室で過ごし、互いの匂いと生活音に落ち着いて反応できることを確認してから短時間の対面を始めます。": "Begin with complete separation and only start brief introductions after both cats are calm with each other's scent and sounds.",
  "隔離できる部屋があります。先住猫の健康記録も提出できます。": "I have a separate room and can provide my existing cat's health records.",
  "必要事項を確認中です。家族と相談してからプロファイルを提出します。": "I am reviewing the requirements and will submit my profile after speaking with my family.",
  "朝夕の運動に加えて、休日に必要な活動量とトレーニングについて相談したいです。": "I would like advice on weekend activity and training in addition to morning and evening exercise.",
  "毎日の散歩に加え、匂い探しや基礎トレーニングを短時間ずつ行う計画を推奨します。休息時間も必要です。": "Alongside daily walks, we recommend short scent games and basic training, with adequate rest.",
  "平日は朝夕、休日は公園での運動と室内トレーニングを組み合わせられます。": "On weekdays I can exercise morning and evening, and at weekends combine park exercise with indoor training.",
  "トライアル結果と双方の確認記録を受領しました。現在は最終判断を確認しています。": "We received the trial results and both parties' confirmations. The final decision is now being reviewed.",
  "小学生の子どもがいる家庭でも応募できますか。猫が落ち着ける部屋は用意できます。": "Can a household with a primary-school child apply? We can provide a quiet room for the cat.",
  "応募は可能です。大きな声や急な接触を避け、猫から近づくまで待てることを家族全員で確認してください。": "You may apply. Please confirm that everyone can avoid loud noise and sudden contact and wait for the cat to approach.",
  "家族で相談しましたが、今は静かな環境を十分に保てないため、今回は相談のみで終了します。": "After discussing it as a family, we cannot currently maintain a sufficiently quiet environment, so we will end this as an enquiry only.",
  "test 返信です。譲渡者として返信欄の表示を確認しました。": "test reply: I checked how the reply field appears for the rehomer.",
  "画面確認中にプロファイル提出の操作を選択しました。": "Profile submission was selected while checking the interface.",
  "このボタンが次のステップですか？ test": "Is this button the next step? test",
  "短い返信を入力し、会話履歴が読みやすく表示されるか確認しました。": "I entered a short reply to check that the conversation history remained readable.",
  "分かりました。次はプロファイル画面を試します。": "Understood. I will try the profile page next.",
  "申込み準備へ進める操作を選択しました。": "The action to proceed towards an application was selected.",
  "相談フォームと連絡先欄を確認しています。": "I am checking the enquiry form and contact field.",
  "次へ進む前に、必要なケアの詳細を確認してください。返信表示の確認用文章です。": "Please check the care details before continuing. This text is for checking how replies appear.",
  "申込みを審査へ進める操作を行いました。": "The application was moved into review.",
  "test 書類をアップロード／次へボタンを確認": "test document uploaded / next button checked",
  "test 返信": "test reply",
  "ペットのプロファイルを開いてから、この相談画面へ戻る操作を試しました。": "I tried opening the pet profile and returning to this enquiry.",
  "確認用の申込みを面談工程へ進めました。": "The test application was moved to the meeting stage.",
  "譲渡者への直接の質問が、履歴上でどのように見えるか確認しています。": "I am checking how direct questions to the rehomer appear in the history.",
  "日々のお世話と受け渡し方法について、実務を想定した返信を入力しました。": "I entered a practical reply about daily care and handover arrangements.",
  "審査へ引き継ぐ操作を選択しました。": "The action to hand the enquiry into review was selected.",
  "test test／ステータス表示を確認": "test test / checked the status display",
  "test のみの相談です。申込みを開始せず、会話だけを確認します。": "test enquiry only: checking the conversation without starting an application.",
  "test 返信：申込み前でも日々のお世話について相談できます。": "test reply: daily care can be discussed before applying.",
  "ありがとうございます。今日は相談の流れだけを確認します。": "Thank you. I am only checking the enquiry flow today.",
  "相談のみで終了し、審査ケースは作成しませんでした。": "Closed as an enquiry only; no review case was created.",
  "大型犬の飼育経験はありません。必要な運動量と、初心者が準備すべきことを教えてください。": "I have not cared for a large dog before. Please explain the exercise required and what a first-time owner should prepare.",
  "朝夕それぞれ45分前後の散歩に加え、室内での知育遊びが必要です。大型犬を安全に休ませられる場所と、滑りにくい床もご準備ください。": "In addition to walks of around 45 minutes each morning and evening, indoor enrichment is needed. Please also prepare a safe resting area for a large dog and non-slip flooring.",
  "在宅勤務中の生活リズムと、日中に必要なお世話について確認したいです。": "I would like to check the daily routine and daytime care needed while I work from home.",
  "昼間は同じ部屋で静かに過ごせます。正午頃の食事と投薬、短い遊びの時間を確保してください。会議中に休める別スペースがあると安心です。": "The pet can rest quietly in the same room during the day. Please allow time for a midday meal and medication and a short play session. A separate resting space during meetings would help.",
};
