/** English display copy for the fixed research cases. Japanese remains the study source. */
export const researchCaseTranslations: Record<string, string> = {
  "面談で計画と本人の理解を確認する": "Confirm the plan and the applicant's understanding at the meeting.",
  "大人2名。世話の分担と緊急時の支援者を確認済み。": "Two adults; care duties and emergency support have been confirmed.",
  "この動物の性格とケアの必要性を理解し、落ち着いて関係を築きたい。": "Understands this pet's temperament and care needs and wants to build a calm relationship.",
  "飼育可能な住居。室内の専用スペースと玄関・窓の脱走防止策を計画済み。": "Pet-friendly housing, with a dedicated indoor space and escape prevention at doors and windows.",
  "朝夕のお世話を担当し、不在時は支援者が対応。対象動物の日課を継続できる。": "Morning and evening care is planned, with a supporter available during absences to maintain the pet's routine.",
  "対象動物のケアを説明でき、必要な講習・練習を済ませている。": "Can explain the pet's care needs and has completed the necessary learning and practice.",
  "通院先と夜間の移動方法を確認済み。日常費・継続治療費・緊急費の計画がある。": "Has identified a vet and nighttime transport, with plans for daily, ongoing treatment and emergency costs.",
  "先住動物なし。同居者の同意と静かな居場所を確認済み。": "No existing pets; household consent and a quiet space are confirmed.",
  "長期のお世話と譲渡後の報告に同意。入院時の預け先も了承済み。": "Agrees to lifelong care and follow-up reports, with an agreed carer during hospital stays.",
  "シニア猫と継続的な医療": "Senior cat and ongoing medical care",
  "投薬・通院・緊急時の備え": "Medication, veterinary visits and emergency planning",
  "穏やかなシニア猫。朝夕の投薬、3か月ごとの通院、完全室内飼育が必要。急な体調変化に対応できる体制が求められます。": "A gentle senior cat needing morning and evening medication, veterinary visits every three months and indoor-only care. The adopter needs a plan for sudden changes in health.",
  "シニア猫のケア経験12年。朝夕の投薬手順を説明できる。": "Twelve years' experience caring for senior cats; can explain the morning and evening medication routine.",
  "平日10時間不在。夕方の投薬を代わる人はまだ決まっていない。": "Away for ten hours on weekdays; no one has been arranged to give the evening medication.",
  "夕方の投薬担当者と代替手段を相談する": "Discuss who will give the evening medication and a backup plan.",
  "通常の食費は想定しているが、継続治療費・緊急費の計画は未回答。": "Has budgeted for food but has not explained ongoing treatment or emergency costs.",
  "必要な通院と医療費の備えを具体的に確認する": "Clarify the plan for appointments and veterinary expenses.",
  "成猫4匹と同居予定。静養部屋と段階的な導入計画はまだない。": "Four adult cats already live there; no quiet recovery room or gradual introduction plan is in place.",
  "静養場所と先住猫との導入手順を確認する": "Check the quiet space and introduction plan for the resident cats.",
  "初めての猫。投薬の練習を済ませ、支援者と病院による継続支援を手配した。": "First cat, but has practised giving medication and arranged ongoing help from a supporter and a vet.",
  "大人1名。近隣の支援者が不在時と入院時のお世話に同意。": "One adult; a nearby supporter agrees to provide care during absences or hospital stays.",
  "完全室内飼育と住まい": "Indoor-only care and housing",
  "住居の適合性と申告・確認の区別": "Housing suitability and the distinction between a claim and its verification",
  "環境変化が苦手な猫。完全室内飼育、静かな居場所、窓と玄関の脱走防止が必要。": "A cat sensitive to change who needs indoor-only care, a quiet space and escape prevention at windows and doors.",
  "現在の住居はペット不可。引っ越し先も決まっていない。": "The current home does not permit pets, and no new home has been arranged.",
  "飼育可能な住居が確定してから再確認する": "Reassess once pet-friendly housing is secured.",
  "猫の飼育は可能。網戸だけで窓を開け、玄関の二重扉対策は未計画。": "Cats are permitted, but open windows have only screens and no second-door arrangement is planned.",
  "脱走防止策を相談し設置計画を確認する": "Discuss escape prevention and confirm an installation plan.",
  "若い犬の運動とトレーニング": "Exercise and training for a young dog",
  "生活時間と具体的な支援計画": "Daily schedule and practical support",
  "活発な中型犬。朝夕の運動と毎日の短いトレーニングが必要。興奮しやすく、小さな子どもとの接触は慎重に進める。": "An active medium-sized dog needing exercise morning and evening and short daily training. He becomes excited easily, so contact with young children needs care.",
  "朝夕に45分の散歩。遅くなる日は依頼済みの支援者が対応。": "Plans 45-minute walks morning and evening; an arranged supporter helps on late days.",
  "犬のトレーニング経験あり。報酬を使った練習計画を作成済み。": "Has dog-training experience and a reward-based training plan.",
  "平日12時間不在。散歩は週末のみを予定し、平日の支援者はいない。": "Away for twelve hours on weekdays; plans walks only at weekends and has no weekday helper.",
  "毎日の運動と不在時の支援体制を相談する": "Discuss daily exercise and support during absences.",
  "初めての犬。困った行動はそのうち直ると考え、練習・相談先は未計画。": "First dog; assumes difficult behaviour will resolve on its own, with no training or advice plan.",
  "日々の練習と相談先の確保を相談する": "Discuss daily practice and a source of training advice.",
  "幼児と同居。犬と子どもの生活空間を分ける計画はまだない。": "A young child lives in the home; no plan yet separates the child's and dog's spaces.",
  "大人の監督と空間分離の方法を確認する": "Check adult supervision and ways to separate their spaces.",
  "交代勤務だが日課に合わせた散歩担当と代替支援者を確保済み。": "Works shifts but has arranged a walker and backup supporter around the dog's routine.",
  "大人1名。勤務時間に合わせて支援者と役割を分担。": "One adult who shares care with a supporter around work hours.",
  "高い適合点と未確認の住居": "High suitability score, unverified housing",
  "スコアへの過度な依存を観察するケース": "A case for examining over-reliance on scores",
  "落ち着いた大型犬。大型犬の飼育が認められた住居、体重管理、毎日の適度な運動が必要。": "A calm large dog needing housing that permits large dogs, weight management and moderate daily exercise.",
  "大型犬の体重管理について面談で助言を受けたい。日常ケアの計画はある。": "Has a daily care plan and would like advice at the meeting about managing a large dog's weight.",
  "食事量と定期計量の方法を確認する": "Check food portions and regular weighing.",
  "規約では小型犬のみ許可。大型犬の許可変更の見通しはない。": "Housing rules allow only small dogs; there is no prospect of permission for a large dog.",
  "大型犬を飼育できる住居条件を確認する": "Confirm housing conditions for a large dog.",
  "多頭飼育の受入れ体制": "Capacity to take on another pet",
  "頭数と実際のケア能力を区別": "Distinguishing pet count from actual capacity to care",
  "新しい猫に緊張しやすい。隔離できる部屋、段階的な対面、個別の食事・健康管理が必要。": "This cat becomes anxious around unfamiliar cats and needs a separate room, gradual introductions and individual feeding and health care.",
  "猫4匹。独立した静養部屋、個別のケア記録、段階的な対面計画がある。": "Four cats live there, with a separate quiet room, individual care records and a gradual introduction plan.",
  "猫6匹。分離スペースがなく、一斉に同じ部屋へ入れる予定。個別の通院状況も不明。": "Six cats live there; no separate space is available, all would meet at once, and their individual veterinary care is unclear.",
  "分離スペース・導入計画・既存のケア負担を確認する": "Check separation space, introductions and existing care workload.",
  "犬1匹。猫との同居経験はなく、安全に分離する方法は未計画。": "One dog lives there; there is no experience with cats and no safe separation plan.",
  "犬と猫の相性と分離方法を確認する": "Check dog–cat compatibility and separation arrangements.",
  "見た目の好みと動物の生活": "Appearance preferences and the pet's welfare",
  "希望より福祉上の必要条件を優先": "Prioritising welfare needs over preferences",
  "静かな生活を好み、抱っこや大きな音が苦手。完全室内で、触れ合いを強制しない接し方が必要。": "A cat who prefers quiet, dislikes being held and loud sounds, and needs indoor-only care without forced handling.",
  "写真撮影のため毎日抱っこを続け、嫌がっても慣れさせたいと回答。": "Plans to hold the cat daily for photos, even if the cat resists, hoping the cat will get used to it.",
  "嫌がる触れ合いを避ける意思と接し方を確認する": "Check willingness and methods to avoid unwanted handling.",
  "見た目が好み。イベントや写真撮影に連れて行きたい。": "Likes the cat's appearance and wants to take it to events and photo shoots.",
  "室内中心だが、猫が望めば自由に屋外へ出す予定。": "Plans mostly indoor care but would allow the cat outside freely if it seems to want to go.",
  "完全室内飼育の必要性と実施意思を確認する": "Check understanding of and commitment to indoor-only care.",
  "大人1名。静かな生活と不在時の支援を確保。": "One adult with a quiet home and support during absences.",
  "当初は子猫を希望したが、この猫の年齢と接し方を理解して希望を変更した。": "Initially wanted a kitten but changed preference after understanding this cat's age and handling needs.",
  "普段は適合しているが緊急時が未定": "Suitable day to day, but no emergency plan",
  "一つの未解決リスクを総合点で隠さない": "A single unresolved risk must not be hidden by an overall score",
  "穏やかなシニア犬。日々の健康観察と通院の継続が必要。飼い主が急に世話できない場合にも対応できる体制を求める。": "A gentle senior dog needing daily health monitoring and continued veterinary care, including a backup if the owner suddenly cannot provide care.",
  "終生飼育と報告に同意しているが、入院時の預け先は未回答。": "Agrees to lifelong care and updates but has not named a carer during hospital stays.",
  "緊急時に世話を引き継げる支援者を確認する": "Identify someone who can take over care in an emergency.",
  "シニア世代の大人2名。日常の世話と緊急時の支援体制を確保。": "Two older adults with daily care and emergency support arranged.",
  "治療負担が増えた場合は飼育を続けない意向。引継ぎ先も考えていない。": "Would not continue care if treatment becomes more demanding and has not considered a new carer.",
  "継続飼育と困った際の相談・支援計画を確認する": "Discuss long-term care and support when difficulties arise.",
  "属性が違ってもケアの条件は同じ": "Different backgrounds, equivalent care plans",
  "単身・経験・勤務の属性による単純な除外を点検": "Testing simplistic exclusions based on household, experience or work pattern",
  "落ち着いた成犬。朝夕のお世話、室内の居場所、通院と緊急時の備えが必要。": "A calm adult dog needing morning and evening care, an indoor space, veterinary visits and emergency planning.",
  "大人1名。日常の世話と緊急時の支援を確保。": "One adult with daily care and emergency support arranged.",
  "大人2名。日常の世話と緊急時の支援を確保。": "Two adults with daily care and emergency support arranged.",
  "シニア世代の大人1名。日常の世話と緊急時の支援を確保。": "One older adult with daily care and emergency support arranged.",
  "交代勤務の大人1名。日課に合う担当と緊急時の支援を確保。": "One shift worker with care aligned to the daily routine and emergency support arranged.",
  "夕方の投薬体制が未確定": "Evening medication cover is not arranged",
  "不在時間自体ではなく、Bellaの投薬が途切れる可能性を捉える。": "Focus on the risk of missed medication, not absence hours alone.",
  "継続治療と緊急費の備えが不明": "Ongoing treatment and emergency funding are unclear",
  "収入属性ではなく治療継続の具体的な計画を確認する。": "Check the concrete treatment plan, not income categories.",
  "先住猫から離れた静養場所が未確定": "A quiet space away from resident cats is not arranged",
  "頭数だけで拒否せず、スペースと導入計画を確認する。": "Check space and introductions rather than rejecting solely on pet count.",
  "AとDは次の面談へ進める候補。初めての飼育や単身であることだけを理由にDを除外しない。": "A and D may proceed to a meeting. Do not exclude D solely for being a first-time or single-person household.",
  "現在の住居はペット不可": "Current housing does not permit pets",
  "現在の飼育条件の不一致を指摘する。": "Identify the current housing mismatch.",
  "脱走防止が未整備": "Escape prevention is not in place",
  "完全室内飼育を維持する具体策が必要。": "A practical plan is needed to maintain indoor-only care.",
  "住居の申告は良好だが確認待ち": "Housing claim is suitable but unverified",
  "高得点でも確認完了と取り違えない。": "Do not mistake a high score for completed verification.",
  "Aは面談候補。Dは住居確認を追加すれば候補に戻せる。未確認と不適合を区別する。": "A is a meeting candidate. D may become one after housing verification. Distinguish unknown from unsuitable.",
  "毎日の運動・不在時対応が不足": "Daily exercise and absence cover are insufficient",
  "勤務形態ではなく具体的な運動不足を捉える。": "Focus on the unmet exercise need, not work pattern.",
  "トレーニングと相談先が未計画": "Training and advice are not planned",
  "経験の有無だけでなく準備を確認する。": "Check preparation, not experience alone.",
  "幼児との接触管理が未計画": "Supervision around the young child is not planned",
  "同居家族の存在だけで拒否せず安全な空間と監督を相談する。": "Discuss safe space and supervision rather than rejecting because a child is present.",
  "AとDは次の面談候補。交代勤務や単身であること自体は減点しない。": "A and D may proceed to a meeting. Shift work or living alone is not itself a negative factor.",
  "Aの大型犬の飼育許可は未確認": "A's permission to keep a large dog is unverified",
  "100点の準備状況と許可の確認済み状態を混同しない。": "Do not confuse a full planning score with verified permission.",
  "Cの規約は小型犬のみ": "C's housing rules allow only small dogs",
  "大型犬であるLeoの条件と不一致。": "This conflicts with Leo's needs as a large dog.",
  "Dの住居情報・本人確認が未完了": "D's housing and identity checks are incomplete",
  "未確認の重要項目を解消せず先に進めない。": "Do not advance without resolving these important unknowns.",
  "Bには体重管理の追加説明が必要": "B needs further advice about weight management",
  "具体的な助言によって解消できる点を挙げる。": "Identify an issue that practical advice may resolve.",
  "Bへの助言と面談が一つの選択肢。全員を追加確認とする判断も根拠を読んで評価する。点数最高のA/Dを無条件に進めると確認漏れとなる。": "Advice and a meeting for B are one option. Requiring more checks for everyone may also be justified. Advancing high-scoring A or D unconditionally would miss verification.",
  "分離場所と個別ケアの記録がない": "No separate space or individual care records",
  "多頭飼育そのものを病気や虐待と断定せず、具体的負担を捉える。": "Consider practical workload without assuming that keeping several pets implies illness or abuse.",
  "犬との相性・分離計画が未確認": "Dog compatibility and separation plan are unverified",
  "先住動物が少なくても安全な導入が必要。": "Safe introductions matter even with only one resident pet.",
  "AとDは候補。頭数だけを用いる単純な除外を避ける。": "A and D are candidates; avoid excluding solely by pet count.",
  "嫌がる接触を強制する予定": "Plans to force unwanted contact",
  "見た目の一致がストレスのリスクを打ち消さない。": "Matching appearance preferences does not remove the risk of stress.",
  "完全室内飼育の条件と不一致": "Conflicts with the indoor-only condition",
  "飼育方針を具体的に確認する。": "Clarify the actual care plan.",
  "好みそのものを減点せず、実際の接し方と必要条件との一致を見る。": "Do not penalise preferences themselves; assess actual handling against care needs.",
  "入院時の代替ケアが不明": "Backup care during hospital stays is unclear",
  "高い総合点でも一つの重要な欠落を拾う。": "Flag an important gap even when the total score is high.",
  "治療負担が増した際の継続計画がない": "No continued-care plan if treatment becomes more demanding",
  "終生飼育を具体的支援体制とともに確認する。": "Confirm lifelong care together with practical support.",
  "譲渡後の連絡への同意が確認待ち": "Consent to post-adoption contact is pending",
  "未同意と拒否を混同しない。": "Do not confuse unanswered with refused.",
  "Bは候補。年齢区分のみで排除せず、生活と支援計画で判断する。": "B is a candidate. Assess living and support plans rather than age category alone.",
  "4人のケアに関する証拠と確認状態は同一。属性だけで順位を付ける根拠はない。同点は申込み順の安定表示であり優劣ではない。": "All four have equivalent care evidence and verification. Personal characteristics do not justify ranking them. Equal scores retain application order, not a merit order.",
  "この評価では用意された動物・応募者の事例を確認します。実際の譲渡判断は行いません。同じケースを2種類の画面で確認し、選択・判断理由・所要時間・5段階の感想を記録します。氏名、連絡先、所属組織名は入力しないでください。参加は任意で、途中で中止できます。中止ボタンではこのセッションの回答を削除します。結果は匿名コードで研究者が確認し、報告では集計・匿名化します。所要時間には画面外の時間も含まれます。外部提出済みの集計からの撤回方法や保管期間は、実施前に研究者から別途説明を受けてください。": "This evaluation presents prepared pet and applicant cases; it does not make real adoption decisions. You will examine the same cases in two interface modes and record a choice, reasons, time and five-point ratings. Do not enter names, contact details or organisation names. Participation is voluntary and you may stop at any time. The withdrawal button deletes this session's responses. The researcher reviews results under an anonymous code and reports aggregated, anonymised findings. Timing includes time away from the page. Before participation, the researcher will separately explain retention and how withdrawal works after aggregated results have been submitted.",
};
